In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.3'

In [4]:
l=[8,5,2,3,4,7,9]

In [5]:
type(l)

list

In [7]:
x=np.array(l)
print(x)

[8 5 2 3 4 7 9]


In [8]:
type(x)

numpy.ndarray

In [9]:
x[5]

7

In [11]:
np.array([15,21,40,6,84])

array([15, 21, 40,  6, 84])

In [12]:
l1=[5,8,3,4,9,7]
l2=[4,2,3,4,9,8]
l3=[8,2,4,6,9,2]

In [13]:
arr=np.array([l1,l2,l3])

In [14]:
arr

array([[5, 8, 3, 4, 9, 7],
       [4, 2, 3, 4, 9, 8],
       [8, 2, 4, 6, 9, 2]])

In [15]:
print(type(arr))

<class 'numpy.ndarray'>


In [16]:
arr.shape

(3, 6)

In [17]:
arr[0:2,1:2]

array([[8],
       [2]])

In [20]:
arr[0:2,0:4]

array([[5, 8, 3, 4],
       [4, 2, 3, 4]])

In [19]:
arr[0:3,1:3]

array([[8, 3],
       [2, 3],
       [2, 4]])

In [21]:
arr

array([[5, 8, 3, 4, 9, 7],
       [4, 2, 3, 4, 9, 8],
       [8, 2, 4, 6, 9, 2]])

In [22]:
arr[0:3,3:5]

array([[4, 9],
       [4, 9],
       [6, 9]])

In [30]:
arr[1:3,3:5]

array([[4, 9],
       [6, 9]])

In [31]:
arr[0:3,2:4]

array([[3, 4],
       [3, 4],
       [4, 6]])

In [32]:
#mechanism to create an array

In [33]:
""""
1.Array()
2.arange()
3.linspace()
4.logspace()
5.zeros()
6.ones()
"""

'"\n1.Array()\n2.arange()\n3.linspace()\n4.logspace()\n5.zeros()\n6.ones()\n'

In [34]:
x=np.arange(20)

In [35]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
x=np.arange(1,20,2)

In [38]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
x=np.arange(0,50)

In [42]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
x=np.arange(1,50,3)

In [44]:
x

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [45]:
x=np.arange(0,50).reshape(5,10)

In [46]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [50]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [53]:
np.logspace(0,50,5)

array([1.00000000e+00, 3.16227766e+12, 1.00000000e+25, 3.16227766e+37,
       1.00000000e+50])

In [54]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [58]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [59]:
np.ones((1,50))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

In [64]:
np.random.rand(3,6)

array([[0.06721355, 0.11253599, 0.33883038, 0.99457607, 0.31355614,
        0.95955725],
       [0.37782811, 0.1524476 , 0.20743149, 0.13620323, 0.86566455,
        0.8308751 ],
       [0.14798917, 0.95419072, 0.08290835, 0.79428919, 0.49552697,
        0.82649844]])

In [66]:
np.random.randn(7)

array([ 0.63438494, -1.02370792, -0.72798019,  0.82202794, -0.78488963,
        0.98399286, -0.54720355])

In [69]:
np.random.ranf(3)

array([0.89126102, 0.07046155, 0.60145734])

In [71]:
np.random.randint(5,30,5)

array([29, 14,  7,  9, 18])

In [72]:
np.random.randint(5,20,5)

array([ 7, 13, 15, 13,  5])

In [73]:
#pandas

In [75]:
import pandas as pd
import numpy as np

In [82]:
data=np.arange(0,20).reshape(4,5)

In [83]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
df=pd.DataFrame(data)

In [85]:
df

,0,1,2,3,4
0,0,1,2,3,4
1,5,6,7,8,9
2,10,11,12,13,14
3,15,16,17,18,19


In [87]:
df=pd.DataFrame(data=np.arange(0,20).reshape(4,5),
               columns=["cow","dog","goat","sheep","cat"],
               index=["height","weight","size","color"])

In [88]:
df

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
weight,5,6,7,8,9
size,10,11,12,13,14
color,15,16,17,18,19


In [89]:
df.shape 

(4, 5)

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, height to color
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cow     4 non-null      int64
 1   dog     4 non-null      int64
 2   goat    4 non-null      int64
 3   sheep   4 non-null      int64
 4   cat     4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes


In [94]:
df.describe()

,cow,dog,goat,sheep,cat
count,4.000000,4.000000,4.000000,4.000000,4.000000
mean,7.500000,8.500000,9.500000,10.500000,11.500000
std,6.454972,6.454972,6.454972,6.454972,6.454972
min,0.000000,1.000000,2.000000,3.000000,4.000000
25%,3.750000,4.750000,5.750000,6.750000,7.750000
50%,7.500000,8.500000,9.500000,10.500000,11.500000
75%,11.250000,12.250000,13.250000,14.250000,15.250000
max,15.000000,16.000000,17.000000,18.000000,19.000000


In [95]:
df.isnull()

,cow,dog,goat,sheep,cat
height,False,False,False,False,False
weight,False,False,False,False,False
size,False,False,False,False,False
color,False,False,False,False,False


In [96]:
df.isnull().sum()

cow      0
dog      0
goat     0
sheep    0
cat      0
dtype: int64

In [98]:
df.head(2)

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
weight,5,6,7,8,9


In [101]:
df.tail(3)

,cow,dog,goat,sheep,cat
weight,5,6,7,8,9
size,10,11,12,13,14
color,15,16,17,18,19


In [102]:
df["goat"]

height     2
weight     7
size      12
color     17
Name: goat, dtype: int64

In [105]:
df[["dog","cat"]]

,dog,cat
height,1,4
weight,6,9
size,11,14
color,16,19


In [107]:
df.loc["height"]

cow      0
dog      1
goat     2
sheep    3
cat      4
Name: height, dtype: int64

In [108]:
df.loc[["height","color"]]

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
color,15,16,17,18,19


In [109]:
df

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
weight,5,6,7,8,9
size,10,11,12,13,14
color,15,16,17,18,19


In [110]:
df.iloc[1:3,1:3]

,dog,goat
weight,6,7
size,11,12


In [114]:
df.iloc[1:3,2:4]

,goat,sheep
weight,7,8
size,12,13


In [115]:
df1=pd.read_csv("housing[1].csv")

In [116]:
df1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND


In [119]:
df1.tail(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND


In [120]:
df1.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY


In [121]:
df1.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000


In [124]:
df1.shape 

(20640, 10)

In [125]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [126]:
#How to deal with null or Nan values

In [127]:
import pandas as pd
import numpy as np

In [131]:
d={
    "Ages":[15,50,42,np.nan,45,56],
    "Weight":[45,np.nan,58,85,56,89],
    "Height":[np.nan,78,np.nan,45,56,36],
    "DOB":[1997,2001,2007,1998,2003,np.nan]
}

In [132]:
d

{'Ages': [15, 50, 42, nan, 45, 56],
 'Weight': [45, nan, 58, 85, 56, 89],
 'Height': [nan, 78, nan, 45, 56, 36],
 'DOB': [1997, 2001, 2007, 1998, 2003, nan]}

In [134]:
df=pd.DataFrame(d)

In [135]:
df.isnull()

,Ages,Weight,Height,DOB
0,False,False,True,False
1,False,True,False,False
2,False,False,True,False
3,True,False,False,False
4,False,False,False,False
5,False,False,False,True


In [136]:
df.isnull().sum()

Ages      1
Weight    1
Height    2
DOB       1
dtype: int64

In [137]:
df.notnull()

,Ages,Weight,Height,DOB
0,True,True,False,True
1,True,False,True,True
2,True,True,False,True
3,False,True,True,True
4,True,True,True,True
5,True,True,True,False


In [138]:
df.notnull().sum()

Ages      5
Weight    5
Height    4
DOB       5
dtype: int64

In [139]:
df.fillna(0)

,Ages,Weight,Height,DOB
0,15.0,45.0,0.0,1997.0
1,50.0,0.0,78.0,2001.0
2,42.0,58.0,0.0,2007.0
3,0.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,0.0


In [140]:
df.fillna(3)

,Ages,Weight,Height,DOB
0,15.0,45.0,3.0,1997.0
1,50.0,3.0,78.0,2001.0
2,42.0,58.0,3.0,2007.0
3,3.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,3.0


In [141]:
df.fillna(method="bfill")

,Ages,Weight,Height,DOB
0,15.0,45.0,78.0,1997.0
1,50.0,58.0,78.0,2001.0
2,42.0,58.0,45.0,2007.0
3,45.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,NaN


In [143]:
df.fillna(method="ffill")

,Ages,Weight,Height,DOB
0,15.0,45.0,NaN,1997.0
1,50.0,45.0,78.0,2001.0
2,42.0,58.0,78.0,2007.0
3,42.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,2003.0


In [145]:
df.interpolate(method="linear",limit_direction="both")

,Ages,Weight,Height,DOB
0,15.0,45.0,78.0,1997.0
1,50.0,51.5,78.0,2001.0
2,42.0,58.0,61.5,2007.0
3,43.5,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,2003.0


In [146]:
df.replace(np.nan,4)

,Ages,Weight,Height,DOB
0,15.0,45.0,4.0,1997.0
1,50.0,4.0,78.0,2001.0
2,42.0,58.0,4.0,2007.0
3,4.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,4.0


In [152]:
d={
    "Ages":[15,50,42,4,45,56],
    "Weight":[45,np.nan,58,85,56,89],
    "Height":[np.nan,78,np.nan,45,56,36],
    "DOB":[1997,2001,2007,1998,2003,np.nan]
}

In [153]:
df=pd.DataFrame(d)

In [154]:
df

,Ages,Weight,Height,DOB
0,15,45.0,NaN,1997.0
1,50,NaN,78.0,2001.0
2,42,58.0,NaN,2007.0
3,4,85.0,45.0,1998.0
4,45,56.0,56.0,2003.0
5,56,89.0,36.0,NaN


In [155]:
df.dropna()

,Ages,Weight,Height,DOB
3,4,85.0,45.0,1998.0
4,45,56.0,56.0,2003.0


In [157]:
df.dropna(axis=1)

,Ages
0,15
1,50
2,42
3,4
4,45
5,56
